function [ T ] = dh_trafo_craig( alpha,a,d,theta )
%DH_TRAFO_CRAIG Summary of this function goes here
%   Returns the 4x4 transformation matrix for given DH parameters according
%   to Craig's interpretation

r11 = cosd(theta(1))*...
    (sind(theta(2)+theta(3))*...
    (-cosd(theta(4))*cosd(theta(5))*cosd(theta(6))+...
    sind(theta(4))*sind(theta(6)))-...
    cos(theta(2)+theta(3))*sind(theta(5))*cosd(theta(6)))-...
    sind(theta(1))*(sind(theta(4))*cosd(theta(5))*cosd(theta(6))+...
    cosd(theta(4))*sind(theta(6)));

r21 = -sind(theta(1))*...
    (sind(theta(2)+theta(3))*...
    (-cosd(theta(4))*cosd(theta(5))*cosd(theta(6))+...
    sind(theta(4))*sind(theta(6)))-...
    cos(theta(2)+theta(3))*sind(theta(5))*cosd(theta(6)))-...
    cosd(theta(1))*(sind(theta(4))*cosd(theta(5))*cosd(theta(6))+...
    cosd(theta(4))*sind(theta(6)));

r31 = -cosd(theta(2)+theta(3))*...
    (cosd(theta(4))*cosd(theta(5))*cosd(theta(6))-...
    sind(theta(4))*sind(theta(6)))+...
    sind(theta(2)+theta(3))*sind(theta(5))*cosd(theta(6));

r12 = cosd(theta(1))*...
    (sind(theta(2)+theta(3))*...
    (-cosd(theta(4))*cosd(theta(5))*cosd(theta(6))-...
    sind(theta(4))*sind(theta(6)))-...
    cos(theta(2)+theta(3))*sind(theta(5))*cosd(theta(6)))-...
    sind(theta(1))*(sind(theta(4))*cosd(theta(5))*cosd(theta(6))+...
    cosd(theta(4))*sind(theta(6)));

r22 = -sind(theta(1))*...
    (sind(theta(2)+theta(3))*...
    (-cosd(theta(4))*cosd(theta(5))*cosd(theta(6))-...
    sind(theta(4))*sind(theta(6)))-...
    cos(theta(2)+theta(3))*sind(theta(5))*cosd(theta(6)))-...
    cosd(theta(1))*(sind(theta(4))*cosd(theta(5))*cosd(theta(6))+...
    cosd(theta(4))*sind(theta(6)));

r32 = -cosd(theta(2)+theta(3))*...
    (cosd(theta(4))*cosd(theta(5))*cosd(theta(6))+...
    sind(theta(4))*sind(theta(6)))+...
    sind(theta(2)+theta(3))*sind(theta(5))*cosd(theta(6));

r13 = cosd(theta(1))*...
    (-sind(theta(2)+theta(3))*cosd(theta(4))*sind(theta(5))+...
    cosd(theta(2)+theta(3))*cosd(theta(5)))-...
    sind(theta(1))*sind(theta(4))*sind(theta(5));

r23 = -sind(theta(1))*...
    (-sind(theta(2)+theta(3))*cosd(theta(4))*sind(theta(5))+...
    cosd(theta(2)+theta(3))*cosd(theta(5)))-...
    cosd(theta(1))*sind(theta(4))*sind(theta(5));

r33 = -cosd(theta(2)+theta(3))*cosd(theta(4))*sind(theta(5))-...
    sind(theta(2)+theta(3))*cosd(theta(5));

T = [ r11 r12 r13 px;
    r21 r22 r23 py;
    r31 r32 r33 pz;
    0 0 0 1];

end

